(setq includeme! '(
("ATOMIC_BOOL_LOCK_FREE" stdatomic.h)
("ATOMIC_CHAR16_LOCK_FREE" stdatomic.h)
("ATOMIC_CHAR32_LOCK_FREE" stdatomic.h)
("ATOMIC_CHAR_LOCK_FREE" stdatomic.h)
("ATOMIC_FLAG_INIT" stdatomic.h)
("ATOMIC_INT_LOCK_FREE" stdatomic.h)
("ATOMIC_LLONG_LOCK_FREE" stdatomic.h)
("ATOMIC_LONG_LOCK_FREE" stdatomic.h)
("ATOMIC_POINTER_LOCK_FREE" stdatomic.h)
("ATOMIC_SHORT_LOCK_FREE" stdatomic.h)
("ATOMIC_VAR_INIT" stdatomic.h)
("ATOMIC_WCHAR_T_LOCK_FREE" stdatomic.h)
("BUFSIZ" stdio.h)
("CHAR_BIT" stdint.h)
("CHAR_MAX" stdint.h)
("CHAR_MIN" stdint.h)
("CIRCLEQ_EMPTY" sys/queue.h)
("CIRCLEQ_FIRST" sys/queue.h)
("CIRCLEQ_HEAD_INITIALIZER" sys/queue.h)
("CIRCLEQ_INIT" sys/queue.h)
("CIRCLEQ_INSERT_AFTER" sys/queue.h)
("CIRCLEQ_INSERT_BEFORE" sys/queue.h)
("CIRCLEQ_INSERT_HEAD" sys/queue.h)
("CIRCLEQ_INSERT_TAIL" sys/queue.h)
("CIRCLEQ_LAST" sys/queue.h)
("CIRCLEQ_LOOP_NEXT" sys/queue.h)
("CIRCLEQ_LOOP_PREV" sys/queue.h)
("CIRCLEQ_NEXT" sys/queue.h)
("CIRCLEQ_PREV" sys/queue.h)
("CIRCLEQ_REMOVE" sys/queue.h)
("CLOCKS_PER_SEC" time.h)
("CMPLX" complex.h)
("CMPLXF" complex.h)
("CMPLXL" complex.h)
("CMSG_ALIGN" sys/socket.h)
("CMSG_DATA" sys/socket.h)
("CMSG_FIRSTHDR" sys/socket.h)
("CMSG_LEN" sys/socket.h)
("CMSG_NXTHDR" sys/socket.h)
("CMSG_SPACE" sys/socket.h)
("CPU_ALLOC" sched.h)
("CPU_ALLOC_SIZE" sched.h)
("CPU_AND" sched.h)
("CPU_AND_S" sched.h)
("CPU_CLR" sched.h)
("CPU_CLR_S" sched.h)
("CPU_COUNT" sched.h)
("CPU_COUNT_S" sched.h)
("CPU_EQUAL" sched.h)
("CPU_EQUAL_S" sched.h)
("CPU_FREE" sched.h)
("CPU_ISSET" sched.h)
("CPU_ISSET_S" sched.h)
("CPU_OR" sched.h)
("CPU_OR_S" sched.h)
("CPU_SET" sched.h)
("CPU_SET_S" sched.h)
("CPU_XOR" sched.h)
("CPU_XOR_S" sched.h)
("CPU_ZERO" sched.h)
("CPU_ZERO_S" sched.h)
("DBL_DIG" stdint.h)
("DBL_EPSILON" stdint.h)
("DBL_MANT_DIG" stdint.h)
("DBL_MAX" stdint.h)
("DBL_MAX_10_EXP" stdint.h)
("DBL_MAX_EXP" stdint.h)
("DBL_MIN" stdint.h)
("DBL_MIN_10_EXP" stdint.h)
("DBL_MIN_EXP" stdint.h)
("DECIMAL_DIG" stdint.h)
("DES_FAILED" rpc/des_crypt.h)
("E2BIG" errno.h)
("EACCESS" errno.h)
("EADDRINUSE" errno.h)
("EADDRNOTAVAIL" errno.h)
("EAFNOSUPPORT" errno.h)
("EAGAIN" errno.h)
("EALREADY" errno.h)
("EBADF" errno.h)
("EBADMSG" errno.h)
("EBUSY" errno.h)
("ECANCELED" errno.h)
("ECHILD" errno.h)
("ECONNABORTED" errno.h)
("ECONNREFUSED" errno.h)
("ECONNRESET" errno.h)
("EDEADLK" errno.h)
("EDESTADDRREQ" errno.h)
("EDOM" errno.h)
("EEXIST" errno.h)
("EFAULT" errno.h)
("EFBIG" errno.h)
("EHOSTUNREACH" errno.h)
("EIDRM" errno.h)
("EILSEQ" errno.h)
("EINPROGRESS" errno.h)
("EINTR" errno.h)
("EINVAL" errno.h)
("EIO" errno.h)
("EISCONN" errno.h)
("EISDIR" errno.h)
("ELOOP" errno.h)
("EMFILE" errno.h)
("EMLINK" errno.h)
("EMSGSIZE" errno.h)
("ENAMETOOLONG" errno.h)
("ENETDOWN" errno.h)
("ENETRESET" errno.h)
("ENETUNREACH" errno.h)
("ENFILE" errno.h)
("ENOBUFS" errno.h)
("ENODATA" errno.h)
("ENODEV" errno.h)
("ENOENT" errno.h)
("ENOEXEC" errno.h)
("ENOLCK" errno.h)
("ENOLINK" errno.h)
("ENOMEM" errno.h)
("ENOMSG" errno.h)
("ENOPROTOOPT" errno.h)
("ENOSPC" errno.h)
("ENOSR" errno.h)
("ENOSTR" errno.h)
("ENOSYS" errno.h)
("ENOTCONN" errno.h)
("ENOTDIR" errno.h)
("ENOTEMPTY" errno.h)
("ENOTRECOVERABLE" errno.h)
("ENOTSOCK" errno.h)
("ENOTSUP" errno.h)
("ENOTTY" errno.h)
("ENXIO" errno.h)
("EOF" stdio.h)
("EOPNOTSUPP" errno.h)
("EOVERFLOW" errno.h)
("EOWNERDEAD" errno.h)
("EPERM" errno.h)
("EPIPE" errno.h)
("EPROTO" errno.h)
("EPROTONOSUPPORT" errno.h)
("EPROTOTYPE" errno.h)
("ERANGE" errno.h)
("EROFS" errno.h)
("ESPIPE" errno.h)
("ESRCH" errno.h)
("ETIME" errno.h)
("ETIMEDOUT" errno.h)
("ETXTBSY" errno.h)
("EWOULDBLOCK" errno.h)
("EXDEV" errno.h)
("EXIT_FAILURE" stdlib.h)
("EXIT_SUCCESS" stdlib.h)
("FD_CLR" sys/select.h)
("FD_ISSET" sys/select.h)
("FD_SET" sys/select.h)
("FD_ZERO" sys/select.h)
("FE_ALL_EXCEPT" fenv.h)
("FE_DFL_ENV" fenv.h)
("FE_DIVBYZERO" fenv.h)
("FE_DOWNWARD" fenv.h)
("FE_INEXACT" fenv.h)
("FE_INVALID" fenv.h)
("FE_OVERFLOW" fenv.h)
("FE_TONEAREST" fenv.h)
("FE_TOWARDZERO" fenv.h)
("FE_UNDERFLOW" fenv.h)
("FE_UPWARD" fenv.h)
("FILE" stdio.h)
("FILENAME_MAX" stdio.h)
("FLT_DIG" stdint.h)
("FLT_EPSILON" stdint.h)
("FLT_EVAL_METHOD" float.h)
("FLT_MANT_DIG" stdint.h)
("FLT_MAX" stdint.h)
("FLT_MAX_10_EXP" stdint.h)
("FLT_MAX_EXP" stdint.h)
("FLT_MIN" stdint.h)
("FLT_MIN_10_EXP" stdint.h)
("FLT_MIN_EXP" stdint.h)
("FLT_RADIX" stdint.h)
("FLT_ROUNDS" float.h)
("FOPEN_MAX" stdio.h)
("FP_INFINITE" math.h)
("FP_NAN" math.h)
("FP_NORMAL" math.h)
("FP_SUBNORMAL" math.h)
("FP_ZERO" math.h)
("HUGE_VAL" math.h)
("HUGE_VALF" math.h)
("HUGE_VALL" math.h)
("INT16_MAX" stdint.h)
("INT16_MIN" stdint.h)
("INT32_MAX" stdint.h)
("INT32_MIN" stdint.h)
("INT64_MAX" stdint.h)
("INT64_MIN" stdint.h)
("INT8_MAX" stdint.h)
("INT8_MIN" stdint.h)
("INTMAX_MAX" stdint.h)
("INTMAX_MIN" stdint.h)
("INTPTR_MAX" stdint.h)
("INTPTR_MIN" stdint.h)
("INT_FAST16_MAX" stdint.h)
("INT_FAST16_MIN" stdint.h)
("INT_FAST32_MAX" stdint.h)
("INT_FAST32_MIN" stdint.h)
("INT_FAST64_MAX" stdint.h)
("INT_FAST64_MIN" stdint.h)
("INT_FAST8_MAX" stdint.h)
("INT_FAST8_MIN" stdint.h)
("INT_LEAST16_MAX" stdint.h)
("INT_LEAST16_MIN" stdint.h)
("INT_LEAST32_MAX" stdint.h)
("INT_LEAST32_MIN" stdint.h)
("INT_LEAST64_MAX" stdint.h)
("INT_LEAST64_MIN" stdint.h)
("INT_LEAST8_MAX" stdint.h)
("INT_LEAST8_MIN" stdint.h)
("INT_MAX" stdint.h)
("INT_MIN" stdint.h)
("LC_ALL" locale.h)
("LC_COLLATE" locale.h)
("LC_CTYPE" locale.h)
("LC_MONETARY" locale.h)
("LC_NUMERIC" locale.h)
("LC_TIME" locale.h)
("LDBL_DIG" stdint.h)
("LDBL_EPSILON" stdint.h)
("LDBL_MANT_DIG" stdint.h)
("LDBL_MAX" stdint.h)
("LDBL_MAX_10_EXP" stdint.h)
("LDBL_MAX_EXP" stdint.h)
("LDBL_MIN" stdint.h)
("LDBL_MIN_10_EXP" stdint.h)
("LDBL_MIN_EXP" stdint.h)
("LLONG_MAX" stdint.h)
("LLONG_MIN" stdint.h)
("LONG_MAX" stdint.h)
("LONG_MIN" stdint.h)
("L_tmpnam" stdio.h)
("MB_LEN_MAX" stdint.h)
("NLMSG_ALIGN" asm/types.h linux/netlink.h)
("NLMSG_DATA" asm/types.h linux/netlink.h)
("NLMSG_LENGTH" asm/types.h linux/netlink.h)
("NLMSG_NEXT" asm/types.h linux/netlink.h)
("NLMSG_OK" asm/types.h linux/netlink.h)
("NLMSG_PAYLOAD" asm/types.h linux/netlink.h)
("NLMSG_SPACE" asm/types.h linux/netlink.h)
("NULL" stddef.h)
("ONCE_FLAG_INIT" threads.h)
("PRIX16" stdint.h)
("PRIX32" stdint.h)
("PRIX64" stdint.h)
("PRIX8" stdint.h)
("PRIXFAST16" stdint.h)
("PRIXFAST32" stdint.h)
("PRIXFAST64" stdint.h)
("PRIXFAST8" stdint.h)
("PRIXLEAST16" stdint.h)
("PRIXLEAST32" stdint.h)
("PRIXLEAST64" stdint.h)
("PRIXLEAST8" stdint.h)
("PRIXMAX" stdint.h)
("PRIXPTR " stdint.h)
("PRId16" stdint.h)
("PRId32" stdint.h)
("PRId64" stdint.h)
("PRId8" stdint.h)
("PRIdFAST16" stdint.h)
("PRIdFAST32" stdint.h)
("PRIdFAST64" stdint.h)
("PRIdFAST8" stdint.h)
("PRIdLEAST16" stdint.h)
("PRIdLEAST32" stdint.h)
("PRIdLEAST64" stdint.h)
("PRIdLEAST8" stdint.h)
("PRIdMAX" stdint.h)
("PRIdPTR " stdint.h)
("PRIi16" stdint.h)
("PRIi32" stdint.h)
("PRIi64" stdint.h)
("PRIi8" stdint.h)
("PRIiFAST16" stdint.h)
("PRIiFAST32" stdint.h)
("PRIiFAST64" stdint.h)
("PRIiFAST8" stdint.h)
("PRIiLEAST16" stdint.h)
("PRIiLEAST32" stdint.h)
("PRIiLEAST64" stdint.h)
("PRIiLEAST8" stdint.h)
("PRIiMAX" stdint.h)
("PRIiPTR " stdint.h)
("PRIo16" stdint.h)
("PRIo32" stdint.h)
("PRIo64" stdint.h)
("PRIo8" stdint.h)
("PRIoFAST16" stdint.h)
("PRIoFAST32" stdint.h)
("PRIoFAST64" stdint.h)
("PRIoFAST8" stdint.h)
("PRIoLEAST16" stdint.h)
("PRIoLEAST32" stdint.h)
("PRIoLEAST64" stdint.h)
("PRIoLEAST8" stdint.h)
("PRIoMAX" stdint.h)
("PRIoPTR " stdint.h)
("PRIu16" stdint.h)
("PRIu32" stdint.h)
("PRIu64" stdint.h)
("PRIu8" stdint.h)
("PRIuFAST16" stdint.h)
("PRIuFAST32" stdint.h)
("PRIuFAST64" stdint.h)
("PRIuFAST8" stdint.h)
("PRIuLEAST16" stdint.h)
("PRIuLEAST32" stdint.h)
("PRIuLEAST64" stdint.h)
("PRIuLEAST8" stdint.h)
("PRIuMAX" stdint.h)
("PRIuPTR " stdint.h)
("PRIx16" stdint.h)
("PRIx32" stdint.h)
("PRIx64" stdint.h)
("PRIx8" stdint.h)
("PRIxFAST16" stdint.h)
("PRIxFAST32" stdint.h)
("PRIxFAST64" stdint.h)
("PRIxFAST8" stdint.h)
("PRIxLEAST16" stdint.h)
("PRIxLEAST32" stdint.h)
("PRIxLEAST64" stdint.h)
("PRIxLEAST8" stdint.h)
("PRIxMAX" stdint.h)
("PRIxPTR " stdint.h)
("PTRDIFF_MAX" stdint.h)
("PTRDIFF_MIN" stdint.h)
("RAND_MAX" stdlib.h)
("RTA_DATA" linux/rtnetlink.h asm/types.h sys/socket.h linux/netlink.h)
("RTA_LENGTH" linux/rtnetlink.h asm/types.h sys/socket.h linux/netlink.h)
("RTA_NEXT" linux/rtnetlink.h asm/types.h sys/socket.h linux/netlink.h)
("RTA_OK" linux/rtnetlink.h asm/types.h sys/socket.h linux/netlink.h)
("RTA_PAYLOAD" linux/rtnetlink.h asm/types.h sys/socket.h linux/netlink.h)
("RTA_SPACE" linux/rtnetlink.h asm/types.h sys/socket.h linux/netlink.h)
("SCHAR_MAX" stdint.h)
("SCHAR_MIN" stdint.h)
("SCNX16" stdint.h)
("SCNX32" stdint.h)
("SCNX64" stdint.h)
("SCNX8" stdint.h)
("SCNXFAST16" stdint.h)
("SCNXFAST32" stdint.h)
("SCNXFAST64" stdint.h)
("SCNXFAST8" stdint.h)
("SCNXLEAST16" stdint.h)
("SCNXLEAST32" stdint.h)
("SCNXLEAST64" stdint.h)
("SCNXLEAST8" stdint.h)
("SCNXMAX" stdint.h)
("SCNXPTR" stdint.h)
("SCNd16" stdint.h)
("SCNd32" stdint.h)
("SCNd64" stdint.h)
("SCNd8" stdint.h)
("SCNdFAST16" stdint.h)
("SCNdFAST32" stdint.h)
("SCNdFAST64" stdint.h)
("SCNdFAST8" stdint.h)
("SCNdLEAST16" stdint.h)
("SCNdLEAST32" stdint.h)
("SCNdLEAST64" stdint.h)
("SCNdLEAST8" stdint.h)
("SCNdMAX" stdint.h)
("SCNdPTR " stdint.h)
("SCNi16" stdint.h)
("SCNi32" stdint.h)
("SCNi64" stdint.h)
("SCNi8" stdint.h)
("SCNiFAST16" stdint.h)
("SCNiFAST32" stdint.h)
("SCNiFAST64" stdint.h)
("SCNiFAST8" stdint.h)
("SCNiLEAST16" stdint.h)
("SCNiLEAST32" stdint.h)
("SCNiLEAST64" stdint.h)
("SCNiLEAST8" stdint.h)
("SCNiMAX" stdint.h)
("SCNiPTR " stdint.h)
("SCNo16" stdint.h)
("SCNo32" stdint.h)
("SCNo64" stdint.h)
("SCNo8" stdint.h)
("SCNoFAST16" stdint.h)
("SCNoFAST32" stdint.h)
("SCNoFAST64" stdint.h)
("SCNoFAST8" stdint.h)
("SCNoLEAST16" stdint.h)
("SCNoLEAST32" stdint.h)
("SCNoLEAST64" stdint.h)
("SCNoLEAST8" stdint.h)
("SCNoMAX" stdint.h)
("SCNoPTR " stdint.h)
("SCNu16" stdint.h)
("SCNu32" stdint.h)
("SCNu64" stdint.h)
("SCNu8" stdint.h)
("SCNuFAST16" stdint.h)
("SCNuFAST32" stdint.h)
("SCNuFAST64" stdint.h)
("SCNuFAST8" stdint.h)
("SCNuLEAST16" stdint.h)
("SCNuLEAST32" stdint.h)
("SCNuLEAST64" stdint.h)
("SCNuLEAST8" stdint.h)
("SCNuMAX" stdint.h)
("SCNuPTR " stdint.h)
("SCNx16" stdint.h)
("SCNx32" stdint.h)
("SCNx64" stdint.h)
("SCNx8" stdint.h)
("SCNxFAST16" stdint.h)
("SCNxFAST32" stdint.h)
("SCNxFAST64" stdint.h)
("SCNxFAST8" stdint.h)
("SCNxLEAST16" stdint.h)
("SCNxLEAST32" stdint.h)
("SCNxLEAST64" stdint.h)
("SCNxLEAST8" stdint.h)
("SCNxMAX" stdint.h)
("SCNxPTR " stdint.h)
("SEEK_CUR" stdio.h)
("SEEK_END" stdio.h)
("SEEK_SET" stdio.h)
("SHRT_MAX" stdint.h)
("SHRT_MIN" stdint.h)
("SIGABRT" signal.h)
("SIGFPE" signal.h)
("SIGILL" signal.h)
("SIGINT" signal.h)
("SIGSEGV" signal.h)
("SIGTERM" signal.h)
("SIG_ATOMIC_MAX" stdint.h)
("SIG_ATOMIC_MIN" stdint.h)
("SIG_DFL" signal.h)
("SIG_ERR" signal.h)
("SIG_IGN" signal.h)
("SIZE_MAX" stdint.h)
("SLIST_EMPTY" sys/queue.h)
("SLIST_FIRST" sys/queue.h)
("SLIST_HEAD_INITIALIZER" sys/queue.h)
("SLIST_INIT" sys/queue.h)
("SLIST_INSERT_AFTER" sys/queue.h)
("SLIST_INSERT_HEAD" sys/queue.h)
("SLIST_NEXT" sys/queue.h)
("SLIST_REMOVE" sys/queue.h)
("SLIST_REMOVE_HEAD" sys/queue.h)
("STAILQ_CONCAT" sys/queue.h)
("STAILQ_EMPTY" sys/queue.h)
("STAILQ_FIRST" sys/queue.h)
("STAILQ_HEAD_INITIALIZER" sys/queue.h)
("STAILQ_INIT" sys/queue.h)
("STAILQ_INSERT_AFTER" sys/queue.h)
("STAILQ_INSERT_HEAD" sys/queue.h)
("STAILQ_INSERT_TAIL" sys/queue.h)
("STAILQ_NEXT" sys/queue.h)
("STAILQ_REMOVE" sys/queue.h)
("STAILQ_REMOVE_HEAD" sys/queue.h)
("TAILQ_CONCAT" sys/queue.h)
("TAILQ_EMPTY" sys/queue.h)
("TAILQ_FIRST" sys/queue.h)
("TAILQ_HEAD_INITIALIZER" sys/queue.h)
("TAILQ_INIT" sys/queue.h)
("TAILQ_INSERT_AFTER" sys/queue.h)
("TAILQ_INSERT_BEFORE" sys/queue.h)
("TAILQ_INSERT_HEAD" sys/queue.h)
("TAILQ_INSERT_TAIL" sys/queue.h)
("TAILQ_LAST" sys/queue.h)
("TAILQ_NEXT" sys/queue.h)
("TAILQ_PREV" sys/queue.h)
("TAILQ_REMOVE" sys/queue.h)
("TMP_MAX" stdio.h)
("TSS_DTOR_ITERATIONS" threads.h)
("UCHAR_MAX" stdint.h)
("UINT16_MAX" stdint.h)
("UINT32_MAX" stdint.h)
("UINT64_MAX" stdint.h)
("UINT8_MAX" stdint.h)
("UINTMAX_MAX" stdint.h)
("UINTPTR_MAX" stdint.h)
("UINT_FAST16_MAX" stdint.h)
("UINT_FAST32_MAX" stdint.h)
("UINT_FAST64_MAX" stdint.h)
("UINT_FAST8_MAX" stdint.h)
("UINT_LEAST16_MAX" stdint.h)
("UINT_LEAST32_MAX" stdint.h)
("UINT_LEAST64_MAX" stdint.h)
("UINT_LEAST8_MAX" stdint.h)
("UINT_MAX" stdint.h)
("ULLONG_MAX" stdint.h)
("ULONG_MAX" stdint.h)
("USHRT_MAX" stdint.h)
("WCHAR_MAX" stdint.h)
("WCHAR_MIN" stdint.h)
("WINT_MAX" stdint.h)
("WINT_MIN" stdint.h)
("_Complex_I" complex.h)
("_Exit" unistd.h stdlib.h)
("_I" complex.h)
("_IOFBF" stdio.h)
("_IOLBF" stdio.h)
("_IONBF" stdio.h)
("_Imaginary_I" complex.h)
("__fbufsize" stdio.h stdio_ext.h)
("__flbf" stdio.h stdio_ext.h)
("__fpending" stdio.h stdio_ext.h)
("__fpurge" stdio.h stdio_ext.h)
("__freadable" stdio.h stdio_ext.h)
("__freading" stdio.h stdio_ext.h)
("__fsetlocking" stdio.h stdio_ext.h)
("__fwritable" stdio.h stdio_ext.h)
("__fwriting" stdio.h stdio_ext.h)
("__ppc_get_timebase" sys/platform/ppc.h)
("__ppc_get_timebase_freq" sys/platform/ppc.h)
("__setfpucw" i386/fpu_control.h)
("_exit" unistd.h)
("_flushlbf" stdio.h stdio_ext.h)
("_llseek" unistd.h sys/types.h)
("_sysctl" unistd.h linux/sysctl.h)
("a64l" stdlib.h)
("abort" stdlib.h)
("abs" stdlib.h)
("accept" sys/socket.h sys/types.h)
("accept4" sys/socket.h sys/types.h)
("access" unistd.h)
("acct" unistd.h)
("acos" math.h)
("acosf" math.h)
("acosh" math.h)
("acoshf" math.h)
("acoshl" math.h)
("acosl" math.h)
("add_key" sys/types.h keyutils.h)
("addmntent" stdio.h mntent.h)
("addseverity" fmtmsg.h)
("adjtime" sys/time.h)
("adjtimex" sys/timex.h)
("aio_cancel" aio.h)
("aio_error" aio.h)
("aio_fsync" aio.h)
("aio_init" aio.h)
("aio_read" aio.h)
("aio_return" aio.h)
("aio_suspend" aio.h)
("aio_write" aio.h)
("alarm" unistd.h)
("aligned_alloc" stdlib.h)
("alloca" alloca.h)
("alphasort" dirent.h)
("arch_prctl" asm/prctl.h sys/prctl.h)
("argz_add" argz.h)
("argz_add_sep" argz.h)
("argz_append" argz.h)
("argz_count" argz.h)
("argz_create" argz.h)
("argz_create_sep" argz.h)
("argz_delete" argz.h)
("argz_extract" argz.h)
("argz_insert" argz.h)
("argz_next" argz.h)
("argz_replace" argz.h)
("argz_stringify" argz.h)
("asctime" time.h)
("asctime_r" time.h)
("asin" math.h)
("asinf" math.h)
("asinh" math.h)
("asinhf" math.h)
("asinhl" math.h)
("asinl" math.h)
("asprintf" stdio.h)
("assert" assert.h)
("assert_perror" assert.h)
("at_quick_exit" stdlib.h)
("atan" math.h)
("atan2" math.h)
("atan2f" math.h)
("atan2l" math.h)
("atanf" math.h)
("atanh" math.h)
("atanhf" math.h)
("atanhl" math.h)
("atanl" math.h)
("atexit" stdlib.h)
("atof" stdlib.h)
("atoi" stdlib.h)
("atol" stdlib.h)
("atoll" stdlib.h)
("atomic_bool" stdatomic.h)
("atomic_char" stdatomic.h)
("atomic_char16_t" stdatomic.h)
("atomic_char32_t" stdatomic.h)
("atomic_compare_exchange_strong" stdatomic.h)
("atomic_compare_exchange_strong_explicit" stdatomic.h)
("atomic_compare_exchange_weak" stdatomic.h)
("atomic_compare_exchange_weak_explicit" stdatomic.h)
("atomic_exchange" stdatomic.h)
("atomic_exchange_explicit" stdatomic.h)
("atomic_fetch_add" stdatomic.h)
("atomic_fetch_add_explicit" stdatomic.h)
("atomic_fetch_and" stdatomic.h)
("atomic_fetch_and_explicit" stdatomic.h)
("atomic_fetch_or" stdatomic.h)
("atomic_fetch_or_explicit" stdatomic.h)
("atomic_fetch_sub" stdatomic.h)
("atomic_fetch_sub_explicit" stdatomic.h)
("atomic_fetch_xor" stdatomic.h)
("atomic_fetch_xor_explicit" stdatomic.h)
("atomic_flag" stdatomic.h)
("atomic_flag_clear" stdatomic.h)
("atomic_flag_clear_explicit" stdatomic.h)
("atomic_flag_test_and_set" stdatomic.h)
("atomic_flag_test_and_set_explicit" stdatomic.h)
("atomic_init" stdatomic.h)
("atomic_int" stdatomic.h)
("atomic_int_fast16_t" stdatomic.h)
("atomic_int_fast32_t" stdatomic.h)
("atomic_int_fast64_t" stdatomic.h)
("atomic_int_fast8_t" stdatomic.h)
("atomic_int_least16_t" stdatomic.h)
("atomic_int_least32_t" stdatomic.h)
("atomic_int_least64_t" stdatomic.h)
("atomic_int_least8_t" stdatomic.h)
("atomic_intmax_t" stdatomic.h)
("atomic_intprt_t" stdatomic.h)
("atomic_is_lock_free" stdatomic.h)
("atomic_llong" stdatomic.h)
("atomic_load" stdatomic.h)
("atomic_load_explicit" stdatomic.h)
("atomic_long" stdatomic.h)
("atomic_ptrdiff_t" stdatomic.h)
("atomic_schar" stdatomic.h)
("atomic_short" stdatomic.h)
("atomic_signal_fence" stdatomic.h)
("atomic_size_t" stdatomic.h)
("atomic_store" stdatomic.h)
("atomic_store_explicit" stdatomic.h)
("atomic_thread_fence" stdatomic.h)
("atomic_uchar" stdatomic.h)
("atomic_uint" stdatomic.h)
("atomic_uint_fast16_t" stdatomic.h)
("atomic_uint_fast32_t" stdatomic.h)
("atomic_uint_fast64_t" stdatomic.h)
("atomic_uint_fast8_t" stdatomic.h)
("atomic_uint_least16_t" stdatomic.h)
("atomic_uint_least32_t" stdatomic.h)
("atomic_uint_least64_t" stdatomic.h)
("atomic_uint_least8_t" stdatomic.h)
("atomic_uintmax_t" stdatomic.h)
("atomic_uintprt_t" stdatomic.h)
("atomic_ullong" stdatomic.h)
("atomic_ulong" stdatomic.h)
("atomic_ushort" stdatomic.h)
("atomic_wchar_t" stdatomic.h)
("avc_add_callback" selinux/avc.h selinux/selinux.h)
("avc_audit" selinux/avc.h selinux/selinux.h)
("avc_av_stats" selinux/avc.h selinux/selinux.h)
("avc_cache_stats" selinux/avc.h selinux/selinux.h)
("avc_cleanup" selinux/avc.h selinux/selinux.h)
("avc_compute_create" selinux/avc.h selinux/selinux.h)
("avc_compute_member" selinux/avc.h selinux/selinux.h)
("avc_context_to_sid" selinux/avc.h selinux/selinux.h)
("avc_destroy" selinux/avc.h selinux/selinux.h)
("avc_entry_ref_init" selinux/avc.h selinux/selinux.h)
("avc_get_initial_sid" selinux/avc.h selinux/selinux.h)
("avc_has_perm" selinux/avc.h selinux/selinux.h)
("avc_has_perm_noaudit" selinux/avc.h selinux/selinux.h)
("avc_init" selinux/avc.h selinux/selinux.h)
("avc_netlink_open" selinux/avc.h selinux/selinux.h)
("avc_open" selinux/avc.h selinux/selinux.h)
("avc_reset" selinux/avc.h selinux/selinux.h)
("avc_sid_stats" selinux/avc.h selinux/selinux.h)
("avc_sid_to_context" selinux/avc.h selinux/selinux.h)
("basename" libgen.h)
("bcmp" string.h)
("bcopy" string.h)
("bdflush" sys/kdaemon.h)
("be16toh" endian.h)
("be32toh" endian.h)
("be64toh" endian.h)
("bind" sys/socket.h sys/types.h)
("bindresvport" sys/types.h netinet/in.h)
("bpf" linux/bpf.h)
("brk" unistd.h)
("bsd_signal" signal.h)
("bsearch" stdlib.h)
("btowc" wchar.h)
("bzero" strings.h)
("c16rtomb" uchar.h)
("c32rtomb" uchar.h)
("cabs" complex.h)
("cabsf" complex.h)
("cabsl" complex.h)
("cacheflush" asm/cachectl.h)
("cacos" complex.h)
("cacosf" complex.h)
("cacosh" complex.h)
("cacoshf" complex.h)
("cacoshl" complex.h)
("cacosl" complex.h)
("call_once" threads.h)
("calloc" stdlib.h)
("canonicalize_file_name" stdlib.h)
("capget" sys/capability.h)
("capset" sys/capability.h)
("carg" complex.h)
("cargf" complex.h)
("cargl" complex.h)
("casin" complex.h)
("casinf" complex.h)
("casinh" complex.h)
("casinhf" complex.h)
("casinhl" complex.h)
("casinl" complex.h)
("catan" complex.h)
("catanf" complex.h)
("catanh" complex.h)
("catanhf" complex.h)
("catanhl" complex.h)
("catanl" complex.h)
("catclose" nl_types.h)
("catgets" nl_types.h)
("catopen" nl_types.h)
("cbc_crypt" rpc/des_crypt.h)
("cbrt" math.h)
("cbrtf" math.h)
("cbrtl" math.h)
("ccos" complex.h)
("ccosf" complex.h)
("ccosh" complex.h)
("ccoshf" complex.h)
("ccoshl" complex.h)
("ccosl" complex.h)
("ceil" math.h)
("ceilf" math.h)
("ceill" math.h)
("cexp" complex.h)
("cexp2" complex.h)
("cexp2f" complex.h)
("cexp2l" complex.h)
("cexpf" complex.h)
("cexpl" complex.h)
("cfgetispeed" termios.h unistd.h)
("cfgetospeed" termios.h unistd.h)
("cfmakeraw" termios.h unistd.h)
("cfree" stdlib.h)
("cfsetispeed" termios.h unistd.h)
("cfsetospeed" termios.h unistd.h)
("cfsetspeed" termios.h unistd.h)
("chdir" unistd.h)
("checkPasswdAccess" selinux/selinux.h)
("chmod" sys/stat.h)
("chown" unistd.h)
("chroot" unistd.h)
("cimag" complex.h)
("cimagf" complex.h)
("cimagl" complex.h)
("clearenv" stdlib.h)
("clearerr" stdio.h)
("clearerr_unlocked" stdio.h)
("clock" time.h)
("clock_adjtime" sys/timex.h)
("clock_getcpuclockid" time.h)
("clock_getres" time.h)
("clock_gettime" time.h)
("clock_nanosleep" time.h)
("clock_settime" time.h)
("clock_t" time.h)
("clog" complex.h)
("clog10" complex.h)
("clog10f" complex.h)
("clog10l" complex.h)
("clog2" complex.h)
("clog2f" complex.h)
("clog2l" complex.h)
("clogf" complex.h)
("clogl" complex.h)
("clone" sched.h)
("clone3" sched.h)
("close" unistd.h)
("closedir" sys/types.h dirent.h)
("closelog" syslog.h)
("cnd_broadcast" threads.h)
("cnd_destroy" threads.h)
("cnd_init" threads.h)
("cnd_signal" threads.h)
("cnd_t" threads.h)
("cnd_timedwait" threads.h)
("cnd_wait" threads.h)
("complex" complex.h)
("confstr" unistd.h)
("conj" complex.h)
("conjf" complex.h)
("conjl" complex.h)
("connect" sys/socket.h sys/types.h)
("context_free" selinux/context.h)
("context_new" selinux/context.h)
("context_range_get" selinux/context.h)
("context_range_set" selinux/context.h)
("context_role_get" selinux/context.h)
("context_role_set" selinux/context.h)
("context_str" selinux/context.h)
("context_type_get" selinux/context.h)
("context_type_set" selinux/context.h)
("context_user_get" selinux/context.h)
("context_user_set" selinux/context.h)
("copy_file_range" unistd.h)
("copysign" math.h)
("copysignf" math.h)
("copysignl" math.h)
("cos" math.h)
("cosf" math.h)
("cosh" math.h)
("coshf" math.h)
("coshl" math.h)
("cosl" math.h)
("cpow" complex.h)
("cpowf" complex.h)
("cpowl" complex.h)
("cproj" complex.h)
("cprojf" complex.h)
("cprojl" complex.h)
("creal" complex.h)
("crealf" complex.h)
("creall" complex.h)
("creat" sys/types.h fcntl.h sys/stat.h)
("create_module" linux/module.h)
("csin" complex.h)
("csinf" complex.h)
("csinh" complex.h)
("csinhf" complex.h)
("csinhl" complex.h)
("csinl" complex.h)
("csqrt" complex.h)
("csqrtf" complex.h)
("csqrtl" complex.h)
("ctan" complex.h)
("ctanf" complex.h)
("ctanh" complex.h)
("ctanhf" complex.h)
("ctanhl" complex.h)
("ctanl" complex.h)
("ctermid" stdio.h)
("ctime" time.h)
("ctime_r" time.h)
("cuserid" unistd.h stdio.h)
("daemon" unistd.h)
("dbopen" sys/types.h limits.h fcntl.h db.h)
("des_setparity" rpc/des_crypt.h)
("difftime" time.h)
("dirfd" sys/types.h dirent.h)
("dirname" libgen.h)
("div" stdlib.h)
("dl_iterate_phdr" link.h)
("dladdr" dlfcn.h)
("dladdr1" dlfcn.h)
("dlclose" dlfcn.h)
("dlerror" dlfcn.h)
("dlmopen" dlfcn.h)
("dlopen" dlfcn.h)
("dlsym" dlfcn.h)
("dlvsym" dlfcn.h)
("dn_comp" resolv.h netinet/in.h arpa/nameser.h)
("dn_expand" resolv.h netinet/in.h arpa/nameser.h)
("dprintf" stdio.h)
("drand48_r" stdlib.h)
("drem" math.h)
("dremf" math.h)
("dreml" math.h)
("duplocale" locale.h)
("dysize" time.h)
("eaccess" unistd.h)
("ecb_crypt" rpc/des_crypt.h)
("ecvt" stdlib.h)
("ecvt_r" stdlib.h)
("encrypt" unistd.h)
("encrypt_r" unistd.h crypt.h stdlib.h)
("endaliasent" aliases.h)
("endfsent" fstab.h)
("endmntent" stdio.h mntent.h)
("endnetgrent" netdb.h)
("endrpcent" netdb.h)
("endttyent" ttyent.h)
("envz_add" envz.h)
("envz_entry" envz.h)
("envz_get" envz.h)
("envz_merge" envz.h)
("envz_remove" envz.h)
("envz_strip" envz.h)
("epoll_create" sys/epoll.h)
("epoll_create1" sys/epoll.h)
("epoll_ctl" sys/epoll.h)
("epoll_pwait" sys/epoll.h)
("epoll_wait" sys/epoll.h)
("erand48" stdlib.h)
("erand48_r" stdlib.h)
("erf" math.h)
("erfc" math.h)
("erfcf" math.h)
("erfcl" math.h)
("erff" math.h)
("erfl" math.h)
("err" err.h)
("errno" errno.h)
("error" error.h)
("error_at_line" error.h)
("errx" err.h)
("ether_aton" netinet/ether.h)
("ether_aton_r" netinet/ether.h)
("ether_hostton" netinet/ether.h)
("ether_line" netinet/ether.h)
("ether_ntoa" netinet/ether.h)
("ether_ntoa_r" netinet/ether.h)
("ether_ntohost" netinet/ether.h)
("euidaccess" unistd.h)
("eventfd" sys/eventfd.h)
("execl" unistd.h)
("execle" unistd.h)
("execlp" unistd.h)
("execv" unistd.h)
("execve" unistd.h)
("execveat" unistd.h)
("execvp" unistd.h)
("execvpe" unistd.h)
("exit" stdlib.h)
("exit_group" linux/unistd.h)
("exp" math.h)
("exp10" math.h)
("exp10f" math.h)
("exp10l" math.h)
("exp2" math.h)
("exp2f" math.h)
("exp2l" math.h)
("expf" math.h)
("expl" math.h)
("explicit_bzero" strings.h string.h)
("expm1" math.h)
("expm1f" math.h)
("expm1l" math.h)
("fabs" math.h)
("fabsf" math.h)
("fabsl" math.h)
("faccessat" unistd.h fcntl.h)
("faccessat2" unistd.h fcntl.h)
("fallocate" fcntl.h)
("fanotify_init" sys/fanotify.h fcntl.h)
("fanotify_mark" sys/fanotify.h)
("fchdir" unistd.h)
("fchmod" sys/stat.h)
("fchmodat" fcntl.h sys/stat.h)
("fchown" unistd.h)
("fchownat" unistd.h fcntl.h)
("fclose" stdio.h)
("fcntl" unistd.h fcntl.h)
("fcvt" stdlib.h)
("fcvt_r" stdlib.h)
("fdatasync" unistd.h)
("fdim" math.h)
("fdimf" math.h)
("fdiml" math.h)
("fdopen" stdio.h)
("fdopendir" sys/types.h dirent.h)
("feclearexcept" fenv.h)
("fegetenv" fenv.h)
("fegetexceptflag" fenv.h)
("fegetround" fenv.h)
("feholdexcept" fenv.h)
("feof" stdio.h)
("feof_unlocked" stdio.h)
("feraiseexcept" fenv.h)
("ferror" stdio.h)
("ferror_unlocked" stdio.h)
("fesetenv" fenv.h)
("fesetexceptflag" fenv.h)
("fesetround" fenv.h)
("fetestexcept" fenv.h)
("feupdateenv" fenv.h)
("fexecve" unistd.h)
("fflush" stdio.h)
("fflush_unlocked" stdio.h)
("ffs" strings.h)
("ffsl" strings.h string.h)
("ffsll" strings.h string.h)
("fgetc" stdio.h)
("fgetc_unlocked" stdio.h)
("fgetfilecon" selinux/selinux.h)
("fgetfilecon_raw" selinux/selinux.h)
("fgetgrent" sys/types.h grp.h stdio.h)
("fgetgrent_r" grp.h)
("fgetpos" stdio.h)
("fgetpwent" sys/types.h pwd.h stdio.h)
("fgetpwent_r" pwd.h)
("fgets" stdio.h)
("fgets_unlocked" stdio.h)
("fgetspent" shadow.h)
("fgetspent_r" shadow.h)
("fgetss" wchar.h)
("fgetwc" wchar.h)
("fgetwc_unlocked" stdio.h wchar.h)
("fgetws" wchar.h)
("fgetws_unlocked" stdio.h wchar.h)
("fgetxattr" sys/types.h sys/xattr.h)
("fileno" stdio.h)
("fileno_unlocked" stdio.h)
("finite" math.h)
("finitef" math.h)
("finitel" math.h)
("flistxattr" sys/types.h sys/xattr.h)
("flock" sys/file.h)
("flockfile" stdio.h)
("floor" math.h)
("floorf" math.h)
("floorl" math.h)
("fma" math.h)
("fmaf" math.h)
("fmal" math.h)
("fmax" math.h)
("fmaxf" math.h)
("fmaxl" math.h)
("fmemopen" stdio.h)
("fmin" math.h)
("fminf" math.h)
("fminl" math.h)
("fmod" math.h)
("fmodf" math.h)
("fmodl" math.h)
("fmtmsg" fmtmsg.h)
("fnmatch" fnmatch.h)
("fopen" stdio.h)
("fopencookie" stdio.h)
("forkpty" pty.h)
("fpathconf" unistd.h)
("fpclassify" math.h)
("fpos_t" stdio.h)
("fprintf" stdio.h)
("fpurge" stdio.h)
("fputc" stdio.h)
("fputc_unlocked" stdio.h)
("fputs" stdio.h)
("fputs_unlocked" stdio.h)
("fputwc" wchar.h)
("fputwc_unlocked" stdio.h wchar.h)
("fputws" wchar.h)
("fputws_unlocked" stdio.h wchar.h)
("fread" stdio.h)
("fread_unlocked" stdio.h)
("free" stdlib.h)
("freeaddrinfo" sys/socket.h sys/types.h netdb.h)
("freecon" selinux/selinux.h)
("freeconary" selinux/selinux.h)
("freehostent" sys/socket.h sys/types.h netdb.h)
("freeifaddrs" sys/types.h ifaddrs.h)
("freelocale" locale.h)
("freeproc" proc/readproc.h)
("freeproctab" proc/readproc.h)
("fremovexattr" sys/types.h sys/xattr.h)
("freopen" stdio.h)
("frexp" math.h)
("frexpf" math.h)
("frexpl" math.h)
("fscanf" stdio.h)
("fseek" stdio.h)
("fseeko" stdio.h)
("fsetfilecon" selinux/selinux.h)
("fsetfilecon_raw" selinux/selinux.h)
("fsetpos" stdio.h)
("fsetxattr" sys/types.h sys/xattr.h)
("fstat" unistd.h sys/types.h sys/stat.h)
("fstatat" unistd.h sys/types.h fcntl.h sys/stat.h)
("fstatfs" sys/vfs.h)
("fstatvfs" sys/statvfs.h)
("fsync" unistd.h)
("ftell" stdio.h)
("ftello" stdio.h)
("ftime" sys/timeb.h)
("ftok" sys/types.h sys/ipc.h)
("ftruncate" unistd.h sys/types.h)
("ftrylockfile" stdio.h)
("fts_children" sys/types.h fts.h sys/stat.h)
("fts_close" sys/types.h fts.h sys/stat.h)
("fts_open" sys/types.h fts.h sys/stat.h)
("fts_read" sys/types.h fts.h sys/stat.h)
("fts_set" sys/types.h fts.h sys/stat.h)
("ftw" ftw.h)
("funlockfile" stdio.h)
("futex" sys/time.h stdint.h linux/futex.h)
("futimens" fcntl.h sys/stat.h)
("futimes" sys/time.h)
("futimesat" sys/time.h fcntl.h)
("fwide" wchar.h)
("fwprintf" wchar.h)
("fwrite" stdio.h)
("fwrite_unlocked" stdio.h)
("fwscanf" wchar.h)
("gai_cancel" netdb.h)
("gai_error" netdb.h)
("gai_strerror" sys/socket.h sys/types.h netdb.h)
("gai_suspend" netdb.h)
("gamma" math.h)
("gammaf" math.h)
("gammal" math.h)
("gcvt" stdlib.h)
("get_current_dir_name" unistd.h)
("get_default_context" selinux/get_context_list.h selinux/selinux.h)
("get_default_context_with_level" selinux/get_context_list.h selinux/selinux.h)
("get_default_context_with_role" selinux/get_context_list.h selinux/selinux.h)
("get_default_context_with_rolelevel" selinux/get_context_list.h selinux/selinux.h)
("get_default_type" selinux/get_context_list.h selinux/selinux.h)
("get_kernel_syms" linux/module.h)
("get_mempolicy" numaif.h)
("get_nprocs" sys/sysinfo.h)
("get_nprocs_conf" sys/sysinfo.h)
("get_ordered_context_list" selinux/get_context_list.h selinux/selinux.h)
("get_ordered_context_list_with_level" selinux/get_context_list.h selinux/selinux.h)
("get_robust_list" sys/types.h linux/futex.h syscall.h)
("get_thread_area" linux/unistd.h)
("getaddrinfo" sys/socket.h sys/types.h netdb.h)
("getaddrinfo_a" netdb.h)
("getaliasbyname" aliases.h)
("getaliasbyname_r" aliases.h)
("getaliasent" aliases.h)
("getaliasent_r" aliases.h)
("getauxval" sys/auxv.h)
("getc" stdio.h)
("getc_unlocked" stdio.h)
("getchar" stdio.h)
("getchar_unlocked" stdio.h)
("getcon" selinux/selinux.h)
("getcon_raw" selinux/selinux.h)
("getcontext" ucontext.h)
("getcpu" linux/getcpu.h)
("getcwd" unistd.h)
("getdate" time.h)
("getdate_r" time.h)
("getdelim" stdio.h)
("getdents64" dirent.h)
("getdirentries" dirent.h)
("getdomainname" unistd.h)
("getentropy" unistd.h)
("getenv" stdlib.h)
("getexeccon" selinux/selinux.h)
("getexeccon_raw" selinux/selinux.h)
("getfilecon" selinux/selinux.h)
("getfilecon_raw" selinux/selinux.h)
("getfscreatecon" selinux/selinux.h)
("getfscreatecon_raw" selinux/selinux.h)
("getfsent" fstab.h)
("getfsfile" fstab.h)
("getfsspec" fstab.h)
("getgrent_r" grp.h)
("getgrgid" sys/types.h grp.h)
("getgrgid_r" sys/types.h grp.h)
("getgrnam" sys/types.h grp.h)
("getgrnam_r" sys/types.h grp.h)
("getgrouplist" grp.h)
("gethostbyaddr" sys/socket.h netdb.h)
("gethostbyaddr_r" sys/socket.h netdb.h)
("gethostbyname" netdb.h)
("gethostbyname2" sys/socket.h netdb.h)
("gethostbyname2_r" sys/socket.h netdb.h)
("gethostbyname_r" sys/socket.h netdb.h)
("gethostent_r" sys/socket.h netdb.h)
("gethostname" unistd.h)
("getifaddrs" sys/types.h ifaddrs.h)
("getipnodebyaddr" sys/socket.h sys/types.h netdb.h)
("getipnodebyname" sys/socket.h sys/types.h netdb.h)
("getitimer" sys/time.h)
("getkeycreatecon" selinux/selinux.h)
("getkeycreatecon_raw" selinux/selinux.h)
("getline" stdio.h)
("getloadavg" stdlib.h)
("getlogin" unistd.h)
("getlogin_r" unistd.h)
("getmntent" stdio.h mntent.h)
("getmntent_r" stdio.h mntent.h)
("getnameinfo" sys/socket.h netdb.h)
("getnetbyaddr" netdb.h)
("getnetbyaddr_r" netdb.h)
("getnetbyname" netdb.h)
("getnetbyname_r" netdb.h)
("getnetent_r" netdb.h)
("getnetgrent" netdb.h)
("getnetgrent_r" netdb.h)
("getopt" unistd.h)
("getopt_long" unistd.h getopt.h)
("getopt_long_only" unistd.h getopt.h)
("getpass" unistd.h)
("getpeercon" selinux/selinux.h)
("getpeercon_raw" selinux/selinux.h)
("getpeername" sys/socket.h)
("getpgid" unistd.h sys/types.h)
("getpgrp" unistd.h sys/types.h)
("getpidcon" selinux/selinux.h)
("getpidcon_raw" selinux/selinux.h)
("getprevcon" selinux/selinux.h)
("getprevcon_raw" selinux/selinux.h)
("getpriority" sys/time.h sys/resource.h)
("getprotobyname" netdb.h)
("getprotobyname_r" netdb.h)
("getprotobynumber" netdb.h)
("getprotobynumber_r" netdb.h)
("getprotoent_r" netdb.h)
("getpt" stdlib.h)
("getpw" sys/types.h pwd.h)
("getpwent_r" pwd.h)
("getpwnam" sys/types.h pwd.h)
("getpwnam_r" sys/types.h pwd.h)
("getpwuid" sys/types.h pwd.h)
("getpwuid_r" sys/types.h pwd.h)
("getrandom" sys/random.h)
("getresgid" unistd.h)
("getresuid" unistd.h)
("getrlimit" sys/time.h sys/resource.h)
("getrpcbyname" netdb.h)
("getrpcbyname_r" netdb.h)
("getrpcbynumber" netdb.h)
("getrpcbynumber_r" netdb.h)
("getrpcent" netdb.h)
("getrpcent_r" netdb.h)
("getrpcport" rpc/rpc.h)
("getrusage" sys/time.h sys/resource.h)
("gets" stdio.h)
("getservbyname" netdb.h)
("getservbyname_r" netdb.h)
("getservbyport" netdb.h)
("getservbyport_r" netdb.h)
("getservent_r" netdb.h)
("getseuserbyname" selinux/selinux.h)
("getsid" unistd.h sys/types.h)
("getsockcreatecon" selinux/selinux.h)
("getsockcreatecon_raw" selinux/selinux.h)
("getsockname" sys/socket.h)
("getsockopt" sys/socket.h sys/types.h)
("getspent_r" shadow.h)
("getspnam" shadow.h)
("getspnam_r" shadow.h)
("getsubopt" stdlib.h)
("gettimeofday" sys/time.h)
("getttyent" ttyent.h)
("getttynam" ttyent.h)
("getumask" sys/types.h sys/stat.h)
("getunwind" linux/unwind.h syscall.h)
("getutid" utmp.h)
("getutline" utmp.h)
("getutmp" utmpx.h)
("getutmpx" utmpx.h)
("getw" stdio.h)
("getwc" stdio.h wchar.h)
("getwc_unlocked" stdio.h wchar.h)
("getwchar" wchar.h)
("getwchar_unlocked" stdio.h wchar.h)
("getwd" unistd.h)
("getxattr" sys/types.h sys/xattr.h)
("glob" glob.h)
("globfree" glob.h)
("gmtime" time.h)
("gmtime_r" time.h)
("grantpt" stdlib.h)
("group_member" unistd.h)
("gsignal" signal.h)
("hasmntopt" stdio.h mntent.h)
("hcreate" search.h)
("hcreate_r" search.h)
("hdestroy" search.h)
("hdestroy_r" search.h)
("herror" sys/socket.h netdb.h)
("hsearch" search.h)
("hsearch_r" search.h)
("hstrerror" sys/socket.h netdb.h)
("htobe16" endian.h)
("htobe32" endian.h)
("htobe64" endian.h)
("htole16" endian.h)
("htole32" endian.h)
("htole64" endian.h)
("htonl" arpa/inet.h)
("htons" arpa/inet.h)
("hypot" math.h)
("hypotf" math.h)
("hypotl" math.h)
("iconv" iconv.h)
("iconv_close" iconv.h)
("iconv_open" iconv.h)
("if_freenameindex" net/if.h)
("if_indextoname" net/if.h)
("if_nameindex" net/if.h)
("if_nametoindex" net/if.h)
("ilogb" math.h)
("ilogbf" math.h)
("ilogbl" math.h)
("imaginary" complex.h)
("imaxabs" stdlib.h inttypes.h)
("imaxdiv" stdlib.h inttypes.h)
("inb" sys/io.h)
("inb_p" sys/io.h)
("index" strings.h)
("inet_addr" sys/socket.h arpa/inet.h netinet/in.h)
("inet_aton" sys/socket.h arpa/inet.h netinet/in.h)
("inet_lnaof" sys/socket.h arpa/inet.h netinet/in.h)
("inet_makeaddr" sys/socket.h arpa/inet.h netinet/in.h)
("inet_net_ntop" arpa/inet.h)
("inet_net_pton" arpa/inet.h)
("inet_netof" sys/socket.h arpa/inet.h netinet/in.h)
("inet_network" sys/socket.h arpa/inet.h netinet/in.h)
("inet_ntoa" sys/socket.h arpa/inet.h netinet/in.h)
("inet_ntop" arpa/inet.h)
("inet_pton" arpa/inet.h)
("initgroups" sys/types.h grp.h)
("initstate" stdlib.h)
("initstate_r" stdlib.h)
("inl" sys/io.h)
("inl_p" sys/io.h)
("innetgr" netdb.h)
("inotify_add_watch" sys/inotify.h)
("inotify_init" sys/inotify.h)
("inotify_init1" sys/inotify.h)
("inotify_rm_watch" sys/inotify.h)
("insb" sys/io.h)
("insl" sys/io.h)
("insque" search.h)
("insw" sys/io.h)
("int" search.h)
("int16_t" stdint.h)
("int32_t" stdint.h)
("int64_t" stdint.h)
("int8_t" stdint.h)
("int_fast16_t" stdint.h)
("int_fast32_t" stdint.h)
("int_fast64_t" stdint.h)
("int_fast8_t" stdint.h)
("int_least16_t" stdint.h)
("int_least32_t" stdint.h)
("int_least64_t" stdint.h)
("int_least8_t" stdint.h)
("intmax_t" stdint.h)
("intptr_t" stdint.h)
("inw" sys/io.h)
("inw_p" sys/io.h)
("io_cancel" linux/aio_abi.h)
("io_destroy" linux/aio_abi.h)
("io_getevents" linux/time.h linux/aio_abi.h)
("io_setup" linux/aio_abi.h)
("io_submit" linux/aio_abi.h)
("ioctl" sys/ioctl.h)
("ioperm" sys/io.h)
("iopl" sys/io.h)
("iruserok" netdb.h)
("iruserok_af" netdb.h)
("is_context_customizable" selinux/selinux.h)
("isalnum" ctype.h)
("isalnum_l" ctype.h)
("isalpha" ctype.h)
("isalpha_l" ctype.h)
("isascii" ctype.h)
("isascii_l" ctype.h)
("isatty" unistd.h)
("isblank" ctype.h)
("isblank_l" ctype.h)
("iscntrl" ctype.h)
("iscntrl_l" ctype.h)
("isdigit" ctype.h)
("isdigit_l" ctype.h)
("isfdtype" sys/socket.h sys/stat.h)
("isfinite" math.h)
("isgraph" ctype.h)
("isgraph_l" ctype.h)
("isgreater" math.h)
("isgreaterequal" math.h)
("isinf" math.h)
("isinff" math.h)
("isinfl" math.h)
("isless" math.h)
("islessequal" math.h)
("islessgreater" math.h)
("islower" ctype.h)
("islower_l" ctype.h)
("isnan" math.h)
("isnanf" math.h)
("isnanl" math.h)
("isnormal" math.h)
("isprint" ctype.h)
("isprint_l" ctype.h)
("ispunct" ctype.h)
("ispunct_l" ctype.h)
("isspace" ctype.h)
("isspace_l" ctype.h)
("isunordered" math.h)
("isupper" ctype.h)
("isupper_l" ctype.h)
("iswalnum" wctype.h)
("iswalpha" wctype.h)
("iswblank" wctype.h)
("iswcntrl" wctype.h)
("iswctype" wctype.h)
("iswdigit" wctype.h)
("iswgraph" wctype.h)
("iswlower" wctype.h)
("iswprint" wctype.h)
("iswpunct" wctype.h)
("iswspace" wctype.h)
("iswupper" wctype.h)
("iswxdigit" wctype.h)
("isxdigit" ctype.h)
("isxdigit_l" ctype.h)
("j0" math.h)
("j0f" math.h)
("j0l" math.h)
("j1" math.h)
("j1f" math.h)
("j1l" math.h)
("jmp_buf" setjmp.h)
("jn" math.h)
("jnf" math.h)
("jnl" math.h)
("jrand48" stdlib.h)
("jrand48_r" stdlib.h)
("kcmp" linux/kcmp.h)
("kexec_file_load" linux/kexec.h)
("kexec_load" linux/kexec.h)
("key_decryptsession" rpc/rpc.h)
("key_encryptsession" rpc/rpc.h)
("key_gendes" rpc/rpc.h)
("key_secretkey_is_set" rpc/rpc.h)
("key_setsecret" rpc/rpc.h)
("keyctl" sys/types.h keyutils.h)
("kill" sys/types.h signal.h)
("kill_dependency" stdatomic.h)
("killpg" signal.h)
("klogctl" sys/klog.h)
("l64a" stdlib.h)
("labs" stdlib.h)
("lchown" unistd.h)
("lcong48" stdlib.h)
("lcong48_r" stdlib.h)
("lconv" locale.h)
("ldexp" math.h)
("ldexpf" math.h)
("ldexpl" math.h)
("ldiv" stdlib.h)
("le16toh" endian.h)
("le32toh" endian.h)
("le64toh" endian.h)
("lfind" search.h)
("lgamma" math.h)
("lgamma_r" math.h)
("lgammaf" math.h)
("lgammaf_r" math.h)
("lgammal" math.h)
("lgammal_r" math.h)
("lgetfilecon" selinux/selinux.h)
("lgetfilecon_raw" selinux/selinux.h)
("lgetxattr" sys/types.h sys/xattr.h)
("link" unistd.h)
("linkat" unistd.h fcntl.h)
("lio_listio" aio.h)
("listen" sys/socket.h sys/types.h)
("listxattr" sys/types.h sys/xattr.h)
("llabs" stdlib.h)
("lldiv" stdlib.h)
("llistxattr" sys/types.h sys/xattr.h)
("llrint" math.h)
("llrintf" math.h)
("llrintl" math.h)
("llround" math.h)
("llroundf" math.h)
("llroundl" math.h)
("localeconv" locale.h)
("localtime" time.h)
("localtime_r" time.h)
("lockf" unistd.h)
("log" math.h)
("log10" math.h)
("log10f" math.h)
("log10l" math.h)
("log1p" math.h)
("log1pf" math.h)
("log1pl" math.h)
("log2" math.h)
("log2f" math.h)
("log2l" math.h)
("logb" math.h)
("logbf" math.h)
("logbl" math.h)
("logf" math.h)
("login" utmp.h)
("login_tty" pty.h utmp.h)
("logl" math.h)
("logout" utmp.h)
("logwtmp" utmp.h)
("longjmp" setjmp.h)
("lrand48_r" stdlib.h)
("lremovexattr" sys/types.h sys/xattr.h)
("lrint" math.h)
("lrintf" math.h)
("lrintl" math.h)
("lround" math.h)
("lroundf" math.h)
("lroundl" math.h)
("lsearch" search.h)
("lseek" unistd.h sys/types.h)
("lseek64" unistd.h sys/types.h)
("lsetfilecon" selinux/selinux.h)
("lsetfilecon_raw" selinux/selinux.h)
("lsetxattr" sys/types.h sys/xattr.h)
("lstat" unistd.h sys/types.h sys/stat.h)
("lutimes" sys/time.h)
("madvise" sys/mman.h)
("major" sys/sysmacros.h)
("makecontext" ucontext.h)
("makedev" sys/sysmacros.h)
("malloc" stdlib.h)
("malloc_get_state" malloc.h)
("malloc_info" malloc.h)
("malloc_set_state" malloc.h)
("malloc_trim" malloc.h)
("mallopt" malloc.h)
("manual_user_enter_context" selinux/get_context_list.h selinux/selinux.h)
("matchmediacon" selinux/selinux.h)
("matchpathcon" selinux/selinux.h)
("matchpathcon_checkmatches" selinux/selinux.h)
("matchpathcon_filespec_add" selinux/selinux.h)
("matchpathcon_filespec_destroy" selinux/selinux.h)
("matchpathcon_filespec_eval" selinux/selinux.h)
("matchpathcon_fini" selinux/selinux.h)
("matchpathcon_index" selinux/selinux.h)
("matchpathcon_init" selinux/selinux.h)
("matchpathcon_init_prefix" selinux/selinux.h)
("matherr" math.h)
("max_align_t" stddef.h)
("mbind" numaif.h)
("mblen" stdlib.h)
("mbrlen" wchar.h)
("mbrtoc16" uchar.h)
("mbrtoc32" uchar.h)
("mbrtowc" wchar.h)
("mbsinit" wchar.h)
("mbsnrtowcs" wchar.h)
("mbsrtowcs" wchar.h)
("mbstate_t" uchar.h)
("mbstowcs" stdlib.h)
("mbtowc" stdlib.h)
("mcheck" mcheck.h)
("mcheck_pedantic" mcheck.h)
("memalign" stdlib.h malloc.h)
("membarrier" linux/membarrier.h)
("memccpy" string.h)
("memchr" string.h)
("memcmp" string.h)
("memcpy" string.h)
("memfd_create" sys/mman.h)
("memfrob" string.h)
("memmem" string.h)
("memmove" string.h)
("memory_order" stdatomic.h)
("memory_order_acq_rel" stdatomic.h)
("memory_order_acquire" stdatomic.h)
("memory_order_consume" stdatomic.h)
("memory_order_relaxed" stdatomic.h)
("memory_order_release" stdatomic.h)
("memory_order_seq_cst" stdatomic.h)
("mempcpy" string.h)
("memrchr" string.h)
("memset" string.h)
("migrate_pages" numaif.h)
("mincore" unistd.h sys/mman.h)
("minor" sys/sysmacros.h)
("mkdir" sys/types.h sys/stat.h)
("mkdirat" sys/types.h fcntl.h sys/stat.h)
("mkdtemp" stdlib.h)
("mkfifo" sys/types.h sys/stat.h)
("mkfifoat" sys/types.h fcntl.h sys/stat.h)
("mknod" unistd.h sys/types.h fcntl.h sys/stat.h)
("mknodat" unistd.h sys/types.h fcntl.h sys/stat.h)
("mkostemp" stdlib.h)
("mkostemps" stdlib.h)
("mkstemp" stdlib.h)
("mkstemps" stdlib.h)
("mktemp" stdlib.h)
("mktime" time.h)
("mlock" sys/mman.h)
("mlock2" sys/mman.h)
("mlockall" sys/mman.h)
("mmap" sys/mman.h)
("mmap2" sys/mman.h)
("mode_to_security_class" selinux/selinux.h)
("modf" math.h)
("modff" math.h)
("modfl" math.h)
("modify_ldt" sys/types.h)
("mount" sys/mount.h)
("move_pages" numaif.h)
("mpool_close" mpool.h db.h)
("mpool_filter" mpool.h db.h)
("mpool_get" mpool.h db.h)
("mpool_new" mpool.h db.h)
("mpool_open" mpool.h db.h)
("mpool_put" mpool.h db.h)
("mpool_sync" mpool.h db.h)
("mprobe" mcheck.h)
("mprotect" sys/mman.h)
("mq_close" mqueue.h)
("mq_getattr" mqueue.h)
("mq_getsetattr" sys/types.h mqueue.h)
("mq_notify" mqueue.h)
("mq_open" mqueue.h fcntl.h sys/stat.h)
("mq_receive" mqueue.h)
("mq_send" mqueue.h)
("mq_setattr" mqueue.h)
("mq_timedreceive" time.h mqueue.h)
("mq_timedsend" time.h mqueue.h)
("mq_unlink" mqueue.h)
("mrand48_r" stdlib.h)
("mremap" sys/mman.h)
("msgctl" sys/msg.h sys/types.h sys/ipc.h)
("msgget" sys/msg.h sys/types.h sys/ipc.h)
("msgrcv" sys/msg.h sys/types.h sys/ipc.h)
("msgsnd" sys/msg.h sys/types.h sys/ipc.h)
("msync" sys/mman.h)
("mtrace" mcheck.h)
("mtx_destroy" threads.h)
("mtx_init" threads.h)
("mtx_lock" threads.h)
("mtx_plain" threads.h)
("mtx_recursive" threads.h)
("mtx_t" threads.h)
("mtx_timed" threads.h)
("mtx_timedlock" threads.h)
("mtx_trylock" threads.h)
("mtx_unlock" threads.h)
("munlock" sys/mman.h)
("munmap" sys/mman.h)
("muntrace" mcheck.h)
("name_to_handle_at" sys/types.h fcntl.h sys/stat.h)
("nan" math.h)
("nanf" math.h)
("nanl" math.h)
("nanosleep" time.h)
("nearbyint" math.h)
("nearbyintf" math.h)
("nearbyintl" math.h)
("newlocale" locale.h)
("nextafter" math.h)
("nextafterf" math.h)
("nextafterl" math.h)
("nextdown" math.h)
("nextdownf" math.h)
("nextdownl" math.h)
("nexttoward" math.h)
("nexttowardf" math.h)
("nexttowardl" math.h)
("nextup" math.h)
("nextupf" math.h)
("nextupl" math.h)
("nfsservctl" linux/nfsd/syscall.h)
("nftw" ftw.h)
("nice" unistd.h)
("nl_langinfo" langinfo.h)
("nl_langinfo_l" langinfo.h)
("nrand48" stdlib.h)
("nrand48_r" stdlib.h)
("ntohl" arpa/inet.h)
("ntohs" arpa/inet.h)
("ntp_adjtime" sys/timex.h)
("ntp_gettime" sys/timex.h)
("ntp_gettimex" sys/timex.h)
("offsetof" stddef.h)
("on_exit" stdlib.h)
("once_flag" threads.h)
("open" sys/types.h fcntl.h sys/stat.h)
("open_by_handle_at" sys/types.h fcntl.h sys/stat.h)
("open_memstream" stdio.h)
("open_wmemstream" stdio.h wchar.h)
("openat" sys/types.h fcntl.h sys/stat.h)
("openat2" sys/types.h fcntl.h sys/stat.h)
("opendir" sys/types.h dirent.h)
("openlog" syslog.h)
("openpty" pty.h)
("outb" sys/io.h)
("outb_p" sys/io.h)
("outl" sys/io.h)
("outl_p" sys/io.h)
("outsb" sys/io.h)
("outsl" sys/io.h)
("outsw" sys/io.h)
("outw" sys/io.h)
("outw_p" sys/io.h)
("passwd2des" rpc/des_crypt.h)
("pathconf" unistd.h)
("pciconfig_iobase" pci.h)
("pciconfig_read" pci.h)
("pciconfig_write" pci.h)
("pclose" stdio.h)
("pcre2_regerror" pcre2posix.h)
("perf_event_open" linux/perf_event.h linux/hw_breakpoint.h)
("perfmonctl" perfmon.h syscall.h)
("perror" stdio.h)
("personality" sys/personality.h)
("pidfd_open" sys/types.h)
("pidfd_send_signal" signal.h)
("pkey_alloc" sys/mman.h)
("pkey_free" sys/mman.h)
("pkey_mprotect" sys/mman.h)
("poll" poll.h)
("popen" stdio.h)
("posix_fadvise" fcntl.h)
("posix_fallocate" fcntl.h)
("posix_madvise" sys/mman.h)
("posix_memalign" stdlib.h)
("posix_openpt" stdlib.h fcntl.h)
("posix_spawn" spawn.h)
("posix_spawnp" spawn.h)
("pow" math.h)
("pow10" math.h)
("pow10f" math.h)
("pow10l" math.h)
("powf" math.h)
("powl" math.h)
("ppoll" signal.h poll.h)
("prctl" sys/prctl.h)
("pread" unistd.h)
("preadv" sys/uio.h)
("preadv2" sys/uio.h)
("print_access_vector" selinux/selinux.h)
("printf" stdio.h)
("prlimit" sys/time.h sys/resource.h)
("process_vm_readv" sys/uio.h)
("process_vm_writev" sys/uio.h)
("profil" unistd.h)
("pselect" sys/select.h)
("psiginfo" signal.h)
("psignal" signal.h)
("pthread_atfork" pthread.h)
("pthread_attr_destroy" pthread.h)
("pthread_attr_getaffinity_np" pthread.h)
("pthread_attr_getdetachstate" pthread.h)
("pthread_attr_getguardsize" pthread.h)
("pthread_attr_getinheritsched" pthread.h)
("pthread_attr_getschedparam" pthread.h)
("pthread_attr_getschedpolicy" pthread.h)
("pthread_attr_getscope" pthread.h)
("pthread_attr_getsigmask_np" pthread.h)
("pthread_attr_getstack" pthread.h)
("pthread_attr_getstackaddr" pthread.h)
("pthread_attr_getstacksize" pthread.h)
("pthread_attr_init" pthread.h)
("pthread_attr_setaffinity_np" pthread.h)
("pthread_attr_setdetachstate" pthread.h)
("pthread_attr_setguardsize" pthread.h)
("pthread_attr_setinheritsched" pthread.h)
("pthread_attr_setschedparam" pthread.h)
("pthread_attr_setschedpolicy" pthread.h)
("pthread_attr_setscope" pthread.h)
("pthread_attr_setsigmask_np" pthread.h)
("pthread_attr_setstack" pthread.h)
("pthread_attr_setstackaddr" pthread.h)
("pthread_attr_setstacksize" pthread.h)
("pthread_cancel" pthread.h)
("pthread_cleanup_pop" pthread.h)
("pthread_cleanup_pop_restore_np" pthread.h)
("pthread_cleanup_push" pthread.h)
("pthread_cleanup_push_defer_np" pthread.h)
("pthread_cond_broadcast" pthread.h)
("pthread_cond_destroy" pthread.h)
("pthread_cond_init" pthread.h)
("pthread_cond_signal" pthread.h)
("pthread_cond_timedwait" pthread.h)
("pthread_cond_wait" pthread.h)
("pthread_condattr_destroy" pthread.h)
("pthread_condattr_init" pthread.h)
("pthread_create" pthread.h)
("pthread_detach" pthread.h)
("pthread_equal" pthread.h)
("pthread_exit" pthread.h)
("pthread_getaffinity_np" pthread.h)
("pthread_getattr_default_np" pthread.h)
("pthread_getattr_np" pthread.h)
("pthread_getconcurrency" pthread.h)
("pthread_getcpuclockid" time.h pthread.h)
("pthread_getname_np" pthread.h)
("pthread_getschedparam" pthread.h)
("pthread_getspecific" pthread.h)
("pthread_join" pthread.h)
("pthread_key_create" pthread.h)
("pthread_key_delete" pthread.h)
("pthread_kill" signal.h)
("pthread_mutex_consistent" pthread.h)
("pthread_mutex_destroy" pthread.h)
("pthread_mutex_init" pthread.h)
("pthread_mutex_lock" pthread.h)
("pthread_mutex_trylock" pthread.h)
("pthread_mutex_unlock" pthread.h)
("pthread_mutexattr_destroy" pthread.h)
("pthread_mutexattr_getkind_np" pthread.h)
("pthread_mutexattr_getpshared" pthread.h)
("pthread_mutexattr_getrobust" pthread.h)
("pthread_mutexattr_gettype" pthread.h)
("pthread_mutexattr_init" pthread.h)
("pthread_mutexattr_setkind_np" pthread.h)
("pthread_mutexattr_setpshared" pthread.h)
("pthread_mutexattr_setrobust" pthread.h)
("pthread_mutexattr_settype" pthread.h)
("pthread_once" pthread.h)
("pthread_rwlockattr_getkind_np" pthread.h)
("pthread_rwlockattr_setkind_np" pthread.h)
("pthread_setaffinity_np" pthread.h)
("pthread_setattr_default_np" pthread.h)
("pthread_setcancelstate" pthread.h)
("pthread_setcanceltype" pthread.h)
("pthread_setconcurrency" pthread.h)
("pthread_setname_np" pthread.h)
("pthread_setschedparam" pthread.h)
("pthread_setschedprio" pthread.h)
("pthread_setspecific" pthread.h)
("pthread_sigmask" signal.h)
("pthread_sigqueue" signal.h pthread.h)
("pthread_spin_destroy" pthread.h)
("pthread_spin_init" pthread.h)
("pthread_spin_lock" pthread.h)
("pthread_spin_trylock" pthread.h)
("pthread_spin_unlock" pthread.h)
("pthread_timedjoin_np" pthread.h)
("pthread_tryjoin_np" pthread.h)
("ptrace" sys/ptrace.h)
("ptrdiff_t" stddef.h)
("ptsname" stdlib.h)
("ptsname_r" stdlib.h)
("putc" stdio.h)
("putc_unlocked" stdio.h)
("putchar" stdio.h)
("putchar_unlocked" stdio.h)
("putenv" stdlib.h)
("putgrent" grp.h)
("putpwent" sys/types.h pwd.h stdio.h)
("puts" stdio.h)
("putspent" shadow.h)
("pututline" utmp.h)
("putw" stdio.h)
("putwc" stdio.h wchar.h)
("putwc_unlocked" stdio.h wchar.h)
("putwchar" wchar.h)
("putwchar_unlocked" stdio.h wchar.h)
("pvalloc" stdlib.h malloc.h)
("pwrite" unistd.h)
("pwritev" sys/uio.h)
("pwritev2" sys/uio.h)
("qecvt" stdlib.h)
("qecvt_r" stdlib.h)
("qfcvt" stdlib.h)
("qfcvt_r" stdlib.h)
("qgcvt" stdlib.h)
("qsort" stdlib.h)
("qsort_r" stdlib.h)
("query_module" linux/module.h)
("query_user_context" selinux/get_context_list.h selinux/selinux.h)
("quick_exit" stdlib.h)
("quotactl" sys/quota.h xfs/xqm.h)
("raise" signal.h)
("rand" stdlib.h)
("rand_r" stdlib.h)
("random_r" stdlib.h)
("rawmemchr" string.h)
("rcmd" netdb.h)
("rcmd_af" netdb.h)
("re_comp" regex.h sys/types.h)
("re_exec" regex.h sys/types.h)
("read" unistd.h)
("readahead" fcntl.h)
("readdir" dirent.h)
("readdir_r" dirent.h)
("readlink" unistd.h)
("readlinkat" unistd.h fcntl.h)
("readproc" proc/readproc.h)
("readproctab" proc/readproc.h)
("readv" sys/uio.h)
("realloc" stdlib.h)
("reallocarray" stdlib.h)
("realpath" stdlib.h limits.h)
("reboot" linux/reboot.h unistd.h)
("recv" sys/socket.h sys/types.h)
("recvfrom" sys/socket.h sys/types.h)
("recvmsg" sys/socket.h sys/types.h)
("regcomp" regex.h)
("regerror" pcreposix.h)
("regexec" regex.h)
("regfree" regex.h)
("remainder" math.h)
("remainderf" math.h)
("remainderl" math.h)
("remap_file_pages" sys/mman.h)
("remove" stdio.h)
("removexattr" sys/types.h sys/xattr.h)
("remque" search.h)
("remquo" math.h)
("remquof" math.h)
("remquol" math.h)
("rename" stdio.h)
("request_key" sys/types.h keyutils.h)
("res_mkquery" resolv.h netinet/in.h arpa/nameser.h)
("res_nclose" resolv.h netinet/in.h arpa/nameser.h)
("res_ninit" resolv.h netinet/in.h arpa/nameser.h)
("res_nmkquery" resolv.h netinet/in.h arpa/nameser.h)
("res_nquery" resolv.h netinet/in.h arpa/nameser.h)
("res_nquerydomain" resolv.h netinet/in.h arpa/nameser.h)
("res_nsearch" resolv.h netinet/in.h arpa/nameser.h)
("res_nsend" resolv.h netinet/in.h arpa/nameser.h)
("res_query" resolv.h netinet/in.h arpa/nameser.h)
("res_querydomain" resolv.h netinet/in.h arpa/nameser.h)
("res_search" resolv.h netinet/in.h arpa/nameser.h)
("res_send" resolv.h netinet/in.h arpa/nameser.h)
("rewind" stdio.h)
("rewinddir" sys/types.h dirent.h)
("rexec" netdb.h)
("rexec_af" netdb.h)
("rindex" strings.h)
("rint" math.h)
("rintf" math.h)
("rintl" math.h)
("rmdir" unistd.h)
("round" math.h)
("roundf" math.h)
("roundl" math.h)
("rpm_execcon" selinux/selinux.h)
("rpmatch" stdlib.h)
("rresvport" netdb.h)
("rresvport_af" netdb.h)
("rt_sigprocmask" signal.h)
("rtime" rpc/auth_des.h)
("ruserok" netdb.h)
("ruserok_af" netdb.h)
("s390_guarded_storage" asm/guarded_storage.h)
("s390_pci_mmio_read" asm/unistd.h)
("s390_pci_mmio_write" asm/unistd.h)
("s390_runtime_instr" asm/runtime_instr.h)
("s390_sthyi" asm/unistd.h)
("sbrk" unistd.h)
("scalb" math.h)
("scalbf" math.h)
("scalbl" math.h)
("scalbln" math.h)
("scalblnf" math.h)
("scalblnl" math.h)
("scalbn" math.h)
("scalbnf" math.h)
("scalbnl" math.h)
("scandir" dirent.h)
("scandirat" dirent.h fcntl.h)
("scanf" stdio.h)
("sched_get_priority_max" sched.h)
("sched_get_priority_min" sched.h)
("sched_getaffinity" sched.h)
("sched_getattr" sched.h)
("sched_getparam" sched.h)
("sched_getscheduler" sched.h)
("sched_rr_get_interval" sched.h)
("sched_setaffinity" sched.h)
("sched_setattr" sched.h)
("sched_setparam" sched.h)
("sched_setscheduler" sched.h)
("seccomp" linux/filter.h linux/signal.h sys/ptrace.h linux/seccomp.h linux/audit.h)
("secure_getenv" stdlib.h)
("security_av_perm_to_string" selinux/selinux.h)
("security_av_string" selinux/selinux.h)
("security_check_context" selinux/selinux.h)
("security_check_context_raw" selinux/selinux.h)
("security_class_to_string" selinux/selinux.h)
("security_commit_booleans" selinux/selinux.h)
("security_compute_av" selinux/selinux.h)
("security_compute_av_flags" selinux/selinux.h)
("security_compute_av_flags_raw" selinux/selinux.h)
("security_compute_av_raw" selinux/selinux.h)
("security_compute_create" selinux/selinux.h)
("security_compute_create_name" selinux/selinux.h)
("security_compute_create_name_raw" selinux/selinux.h)
("security_compute_create_raw" selinux/selinux.h)
("security_compute_member" selinux/selinux.h)
("security_compute_member_raw" selinux/selinux.h)
("security_compute_relabel" selinux/selinux.h)
("security_compute_relabel_raw" selinux/selinux.h)
("security_compute_user" selinux/selinux.h)
("security_compute_user_raw" selinux/selinux.h)
("security_disable" selinux/selinux.h)
("security_get_boolean_active" selinux/selinux.h)
("security_get_boolean_names" selinux/selinux.h)
("security_get_boolean_pending" selinux/selinux.h)
("security_get_initial_context" selinux/selinux.h)
("security_get_initial_context_raw" selinux/selinux.h)
("security_load_policy" selinux/selinux.h)
("security_set_boolean" selinux/selinux.h)
("security_set_boolean_list" selinux/selinux.h)
("security_setenforce" selinux/selinux.h)
("security_validatetrans" selinux/selinux.h)
("security_validatetrans_raw" selinux/selinux.h)
("seed48" stdlib.h)
("seed48_r" stdlib.h)
("seekdir" dirent.h)
("selabel_close" selinux/label.h selinux/selinux.h)
("selabel_digest" selinux/label.h selinux/selinux.h)
("selabel_get_digests_all_partial_matches" stdbool.h selinux/label.h selinux/selinux.h)
("selabel_lookup" selinux/label.h selinux/selinux.h)
("selabel_lookup_best_match" selinux/label.h selinux/selinux.h)
("selabel_lookup_best_match_raw" selinux/label.h selinux/selinux.h)
("selabel_lookup_raw" selinux/label.h selinux/selinux.h)
("selabel_open" selinux/label.h selinux/selinux.h)
("selabel_partial_match" stdbool.h selinux/label.h selinux/selinux.h)
("selabel_stats" selinux/label.h selinux/selinux.h)
("select" sys/select.h)
("selinux_boolean_sub" selinux/selinux.h)
("selinux_check_access" selinux/selinux.h)
("selinux_check_passwd_access" selinux/selinux.h)
("selinux_check_securetty_context" selinux/selinux.h)
("selinux_file_context_cmp" selinux/selinux.h)
("selinux_file_context_verify" selinux/selinux.h)
("selinux_getenforcemode" selinux/selinux.h)
("selinux_getpolicytype" selinux/selinux.h)
("selinux_init_load_policy" selinux/selinux.h)
("selinux_lsetfilecon_default" selinux/selinux.h)
("selinux_mkload_policy" selinux/selinux.h)
("selinux_raw_context_to_color" selinux/selinux.h)
("selinux_restorecon" selinux/restorecon.h)
("selinux_restorecon_default_handle" selinux/restorecon.h selinux/label.h)
("selinux_restorecon_set_alt_rootpath" selinux/restorecon.h)
("selinux_restorecon_set_exclude_list" selinux/restorecon.h)
("selinux_restorecon_set_sehandle" selinux/restorecon.h selinux/label.h)
("selinux_restorecon_xattr" selinux/restorecon.h)
("selinux_set_callback" selinux/selinux.h)
("selinux_set_mapping" selinux/selinux.h)
("selinux_status_close" selinux/avc.h)
("selinux_status_deny_unknown" selinux/avc.h)
("selinux_status_getenforce" selinux/avc.h)
("selinux_status_open" selinux/avc.h)
("selinux_status_policyload" selinux/avc.h)
("selinux_status_updated" selinux/avc.h)
("sem_close" semaphore.h)
("sem_destroy" semaphore.h)
("sem_getvalue" semaphore.h)
("sem_init" semaphore.h)
("sem_open" semaphore.h fcntl.h sys/stat.h)
("sem_post" semaphore.h)
("sem_timedwait" semaphore.h)
("sem_trywait" semaphore.h)
("sem_unlink" semaphore.h)
("sem_wait" semaphore.h)
("semctl" sys/sem.h sys/types.h sys/ipc.h)
("semget" sys/sem.h sys/types.h sys/ipc.h)
("semop" sys/sem.h sys/types.h sys/ipc.h)
("semtimedop" sys/sem.h sys/types.h sys/ipc.h)
("send" sys/socket.h sys/types.h)
("sendfile" sys/sendfile.h)
("sendmsg" sys/socket.h sys/types.h)
("sendto" sys/socket.h sys/types.h)
("sepol_check_context" sepol/sepol.h)
("sepol_set_policydb_from_file" sepol/sepol.h)
("set_matchpathcon_flags" selinux/selinux.h)
("set_matchpathcon_invalidcon" selinux/selinux.h)
("set_matchpathcon_printf" selinux/selinux.h)
("set_mempolicy" numaif.h)
("set_robust_list" sys/types.h linux/futex.h syscall.h)
("set_thread_area" linux/unistd.h)
("set_tid_address" linux/unistd.h)
("setaliasent" aliases.h)
("setbuf" stdio.h)
("setbuffer" stdio.h)
("setcon" selinux/selinux.h)
("setcon_raw" selinux/selinux.h)
("setcontext" ucontext.h)
("setdomainname" unistd.h)
("setegid" unistd.h sys/types.h)
("setenv" stdlib.h)
("seteuid" unistd.h sys/types.h)
("setexeccon" selinux/selinux.h)
("setexeccon_raw" selinux/selinux.h)
("setexecfilecon" selinux/selinux.h)
("setfilecon" selinux/selinux.h)
("setfilecon_raw" selinux/selinux.h)
("setfscreatecon" selinux/selinux.h)
("setfscreatecon_raw" selinux/selinux.h)
("setfsent" fstab.h)
("setfsgid" sys/fsuid.h)
("setfsuid" sys/fsuid.h)
("setgid" unistd.h sys/types.h)
("sethostent" sys/socket.h netdb.h)
("sethostid" unistd.h)
("sethostname" unistd.h)
("setitimer" sys/time.h)
("setjmp" setjmp.h)
("setkey" unistd.h stdlib.h)
("setkey_r" unistd.h crypt.h stdlib.h)
("setkeycreatecon" selinux/selinux.h)
("setkeycreatecon_raw" selinux/selinux.h)
("setlinebuf" stdio.h)
("setlocale" locale.h)
("setlogmask" syslog.h)
("setmntent" stdio.h mntent.h)
("setnetent" netdb.h)
("setnetgrent" netdb.h)
("setns" sched.h)
("setpgid" unistd.h sys/types.h)
("setpgrp" unistd.h sys/types.h)
("setpriority" sys/time.h sys/resource.h)
("setprotoent" netdb.h)
("setregid" unistd.h sys/types.h)
("setresgid" unistd.h)
("setresuid" unistd.h)
("setreuid" unistd.h sys/types.h)
("setrlimit" sys/time.h sys/resource.h)
("setrpcent" netdb.h)
("setservent" netdb.h)
("setsockcreatecon" selinux/selinux.h)
("setsockcreatecon_raw" selinux/selinux.h)
("setsockopt" sys/socket.h sys/types.h)
("setstate" stdlib.h)
("setstate_r" stdlib.h)
("settimeofday" sys/time.h)
("setttyent" ttyent.h)
("setuid" unistd.h sys/types.h)
("setvbuf" stdio.h)
("setxattr" sys/types.h sys/xattr.h)
("sgetspent" shadow.h)
("sgetspent_r" shadow.h)
("shm_open" sys/stat.h fcntl.h sys/mman.h)
("shm_unlink" sys/stat.h fcntl.h sys/mman.h)
("shmat" sys/shm.h sys/types.h)
("shmctl" sys/shm.h sys/ipc.h)
("shmdt" sys/shm.h sys/types.h)
("shmget" sys/shm.h sys/ipc.h)
("shutdown" sys/socket.h)
("sig_atomic_t" signal.h)
("sigabbrev_np" string.h)
("sigaction" signal.h)
("sigaddset" signal.h)
("sigaltstack" signal.h)
("sigblock" signal.h)
("sigdelset" signal.h)
("sigdescr_np" string.h)
("sigemptyset" signal.h)
("sigfillset" signal.h)
("sighold" signal.h)
("sigignore" signal.h)
("siginterrupt" signal.h)
("sigismember" signal.h)
("siglongjmp" setjmp.h)
("sigmask" signal.h)
("signal" signal.h)
("signalfd" sys/signalfd.h)
("signbit" math.h)
("significand" math.h)
("significandf" math.h)
("significandl" math.h)
("sigpause" signal.h)
("sigpending" signal.h)
("sigprocmask" signal.h)
("sigqueue" signal.h)
("sigrelse" signal.h)
("sigset" signal.h)
("sigsetjmp" setjmp.h)
("sigsetmask" signal.h)
("sigsuspend" signal.h)
("sigtimedwait" signal.h)
("sigvec" signal.h)
("sigwait" signal.h)
("sigwaitinfo" signal.h)
("sin" math.h)
("sincos" math.h)
("sincosf" math.h)
("sincosl" math.h)
("sinf" math.h)
("sinh" math.h)
("sinhf" math.h)
("sinhl" math.h)
("sinl" math.h)
("size_t" stddef.h)
("sleep" unistd.h)
("snprintf" stdio.h)
("sockatmark" sys/socket.h)
("socket" linux/rtnetlink.h asm/types.h sys/socket.h linux/netlink.h)
("socketcall" linux/net.h)
("socketpair" sys/socket.h sys/types.h)
("splice" fcntl.h)
("sprintf" stdio.h)
("spu_create" sys/types.h sys/spu.h)
("spu_run" sys/spu.h)
("sqrt" math.h)
("sqrtf" math.h)
("sqrtl" math.h)
("srand" stdlib.h)
("srand48" stdlib.h)
("srand48_r" stdlib.h)
("srandom" stdlib.h)
("srandom_r" stdlib.h)
("sscanf" stdio.h)
("ssignal" signal.h)
("stat" unistd.h sys/types.h sys/stat.h)
("statfs" sys/vfs.h)
("statvfs" sys/statvfs.h)
("statx" unistd.h sys/types.h fcntl.h sys/stat.h)
("stderr" stdio.h)
("stdin" stdio.h)
("stdout" stdio.h)
("stime" time.h)
("stpcpy" string.h)
("stpncpy" string.h)
("strcasecmp" strings.h)
("strcasestr" string.h)
("strcat" string.h)
("strchr" string.h)
("strchrnul" string.h)
("strcmp" string.h)
("strcoll" string.h)
("strcpy" string.h)
("strcspn" string.h)
("strdup" string.h)
("strdupa" string.h)
("strerror" string.h)
("strerror_l" string.h)
("strerror_r" string.h)
("strerrordesc_np" string.h)
("strerrorname_np" string.h)
("strfmon" monetary.h)
("strfmon_l" monetary.h)
("strfromd" stdlib.h)
("strfromf" stdlib.h)
("strfroml" stdlib.h)
("strfry" strings.h string.h)
("strftime" time.h)
("string_to_av_perm" selinux/selinux.h)
("string_to_security_class" selinux/selinux.h)
("strlen" string.h)
("strncasecmp" strings.h)
("strncat" string.h)
("strncmp" string.h)
("strncpy" string.h)
("strndup" string.h)
("strndupa" string.h)
("strnlen" string.h)
("strpbrk" string.h)
("strptime" time.h)
("strrchr" string.h)
("strsep" string.h)
("strsignal" string.h)
("strspn" string.h)
("strstr" string.h)
("strtod" stdlib.h)
("strtof" stdlib.h)
("strtoimax" inttypes.h)
("strtok" string.h)
("strtok_r" string.h)
("strtol" stdlib.h)
("strtold" stdlib.h)
("strtoll" stdlib.h)
("strtoul" stdlib.h)
("strtoull" stdlib.h)
("strtoumax" inttypes.h)
("strverscmp" string.h)
("strxfrm" string.h)
("swab" unistd.h)
("swapcontext" ucontext.h)
("swapoff" unistd.h sys/swap.h)
("swapon" unistd.h sys/swap.h)
("swprintf" wchar.h)
("swscanf" wchar.h)
("symlink" unistd.h)
("symlinkat" unistd.h fcntl.h)
("sync_file_range" fcntl.h)
("syncfs" unistd.h)
("syscall" unistd.h sys/syscall.h)
("sysconf" unistd.h)
("sysinfo" sys/sysinfo.h)
("syslog" syslog.h)
("system" stdlib.h)
("sysv_signal" signal.h)
("tan" math.h)
("tanf" math.h)
("tanh" math.h)
("tanhf" math.h)
("tanhl" math.h)
("tanl" math.h)
("tcdrain" termios.h unistd.h)
("tcflow" termios.h unistd.h)
("tcflush" termios.h unistd.h)
("tcgetattr" termios.h unistd.h)
("tcgetpgrp" unistd.h)
("tcgetsid" termios.h)
("tcsendbreak" termios.h unistd.h)
("tcsetattr" termios.h unistd.h)
("tcsetpgrp" unistd.h)
("tdelete" search.h)
("tdestroy" search.h)
("tee" fcntl.h)
("telldir" dirent.h)
("tempnam" stdio.h)
("tfind" search.h)
("tgamma" math.h)
("tgammaf" math.h)
("tgammal" math.h)
("thrd_busy" threads.h)
("thrd_create" threads.h)
("thrd_current" threads.h)
("thrd_detach" threads.h)
("thrd_equal" threads.h)
("thrd_error" threads.h)
("thrd_exit" threads.h)
("thrd_join" threads.h)
("thrd_nomem" threads.h)
("thrd_sleep" threads.h)
("thrd_start_t" threads.h)
("thrd_success" threads.h)
("thrd_t" threads.h)
("thrd_timeout" threads.h)
("thrd_yield" threads.h)
("thread_local" threads.h)
("time" time.h)
("time_t" time.h)
("timegm" time.h)
("timelocal" time.h)
("timer_create" signal.h time.h)
("timer_delete" time.h)
("timer_getoverrun" time.h)
("timer_gettime" time.h)
("timer_settime" time.h)
("timeradd" sys/time.h)
("timerclear" sys/time.h)
("timercmp" sys/time.h)
("timerfd_create" sys/timerfd.h)
("timerfd_gettime" sys/timerfd.h)
("timerfd_settime" sys/timerfd.h)
("timerisset" sys/time.h)
("timersub" sys/time.h)
("times" sys/times.h)
("timespec" time.h)
("tm" time.h)
("tmpfile" stdio.h)
("tmpnam" stdio.h)
("tmpnam_r" stdio.h)
("toascii" ctype.h)
("tolower" ctype.h)
("tolower_l" ctype.h)
("toupper" ctype.h)
("toupper_l" ctype.h)
("towctrans" wctype.h)
("towlower" wctype.h)
("towlower_l" wctype.h)
("towupper" wctype.h)
("towupper_l" wctype.h)
("trunc" math.h)
("truncate" unistd.h sys/types.h)
("truncf" math.h)
("truncl" math.h)
("tsearch" search.h)
("tss_create" threads.h)
("tss_delete" threads.h)
("tss_dtor_t" threads.h)
("tss_get" threads.h)
("tss_set" threads.h)
("tss_t" threads.h)
("ttyname" unistd.h)
("ttyname_r" unistd.h)
("ttyslot" unistd.h)
("twalk" search.h)
("twalk_r" search.h)
("ualarm" unistd.h)
("uint16_t" stdint.h)
("uint32_t" stdint.h)
("uint64_t" stdint.h)
("uint8_t" stdint.h)
("uint_fast16_t" stdint.h)
("uint_fast32_t" stdint.h)
("uint_fast64_t" stdint.h)
("uint_fast8_t" stdint.h)
("uint_least16_t" stdint.h)
("uint_least32_t" stdint.h)
("uint_least64_t" stdint.h)
("uint_least8_t" stdint.h)
("uintmax_t" stdint.h)
("uintptr_t" stdint.h)
("ulimit" ulimit.h)
("umask" sys/types.h sys/stat.h)
("umount" sys/mount.h)
("umount2" sys/mount.h)
("uname" sys/utsname.h)
("ungetc" stdio.h)
("ungetwc" wchar.h)
("unlink" unistd.h)
("unlinkat" unistd.h fcntl.h)
("unlockpt" stdlib.h)
("unsetenv" stdlib.h)
("unshare" sched.h)
("updwtmp" utmp.h)
("uselib" unistd.h)
("uselocale" locale.h)
("userfaultfd" linux/userfaultfd.h sys/types.h)
("usleep" unistd.h)
("ustat" unistd.h sys/types.h ustat.h)
("utime" sys/types.h utime.h)
("utimensat" fcntl.h sys/stat.h)
("utimes" sys/time.h sys/types.h utime.h)
("utmpname" utmp.h)
("uuid_clear" uuid.h)
("uuid_compare" uuid.h)
("uuid_copy" uuid.h)
("uuid_generate" uuid.h)
("uuid_generate_md5" uuid.h)
("uuid_generate_random" uuid.h)
("uuid_generate_sha1" uuid.h)
("uuid_generate_time" uuid.h)
("uuid_generate_time_safe" uuid.h)
("uuid_is_null" uuid.h)
("uuid_parse" uuid.h)
("uuid_parse_range" uuid.h)
("uuid_time" uuid.h)
("uuid_unparse" uuid.h)
("uuid_unparse_lower" uuid.h)
("uuid_unparse_upper" uuid.h)
("va_copy" stdarg.h)
("va_end" stdarg.h)
("va_start" stdarg.h)
("valloc" stdlib.h)
("vasprintf" stdio.h)
("vdprintf" stdio.h stdarg.h)
("verr" err.h stdarg.h)
("verrx" err.h stdarg.h)
("versionsort" dirent.h)
("vfprintf" stdio.h)
("vfscanf" stdio.h)
("vfwprintf" wchar.h)
("vfwscanf" wchar.h)
("vm86" sys/vm86.h)
("vm86old" sys/vm86.h)
("vmsplice" sys/uio.h fcntl.h)
("vprintf" stdio.h)
("vscanf" stdio.h)
("vsnprintf" stdio.h)
("vsprintf" stdio.h)
("vsscanf" stdio.h)
("vswprintf" wchar.h)
("vswscanf" wchar.h)
("vsyslog" syslog.h)
("vwarn" err.h stdarg.h)
("vwarnx" err.h stdarg.h)
("vwprintf" wchar.h)
("vwscanf" wchar.h)
("wait" sys/types.h sys/wait.h)
("wait3" sys/time.h sys/types.h sys/wait.h sys/resource.h)
("wait4" sys/time.h sys/types.h sys/wait.h sys/resource.h)
("waitid" sys/types.h sys/wait.h)
("waitpid" sys/types.h sys/wait.h)
("warn" err.h)
("warnx" err.h)
("wcpcpy" wchar.h)
("wcpncpy" wchar.h)
("wcrtomb" wchar.h)
("wcscasecmp" wchar.h)
("wcscat" wchar.h)
("wcschr" wchar.h)
("wcscmp" wchar.h)
("wcscoll" wchar.h)
("wcscpy" wchar.h)
("wcscspn" wchar.h)
("wcsdup" wchar.h)
("wcsftime" wchar.h)
("wcslen" wchar.h)
("wcsncasecmp" wchar.h)
("wcsncat" wchar.h)
("wcsncmp" wchar.h)
("wcsncpy" wchar.h)
("wcsnlen" wchar.h)
("wcsnrtombs" wchar.h)
("wcspbrk" wchar.h)
("wcsrchr" wchar.h)
("wcsrtombs" wchar.h)
("wcsspn" wchar.h)
("wcsstr" wchar.h)
("wcstod" wchar.h)
("wcstof" wchar.h)
("wcstoimax" inttypes.h)
("wcstok" wchar.h)
("wcstol" wchar.h)
("wcstold" wchar.h)
("wcstoll" wchar.h)
("wcstombs" stdlib.h)
("wcstoul" wchar.h)
("wcstoull" wchar.h)
("wcstoumax" inttypes.h)
("wcswidth" wchar.h)
("wcsxfrm" wchar.h)
("wctob" wchar.h)
("wctomb" stdlib.h)
("wctrans" wctype.h)
("wctype" wctype.h)
("wcwidth" wchar.h)
("wmemchr" wchar.h)
("wmemcmp" wchar.h)
("wmemcpy" wchar.h)
("wmemmove" wchar.h)
("wmempcpy" string.h wchar.h)
("wmemset" wchar.h)
("wordexp" wordexp.h)
("wordfree" wordexp.h)
("wprintf" wchar.h)
("write" unistd.h)
("writev" sys/uio.h)
("wscanf" wchar.h)
("xdecrypt" rpc/des_crypt.h)
("xencrypt" rpc/des_crypt.h)
("y0" math.h)
("y0f" math.h)
("y0l" math.h)
("y1" math.h)
("y1f" math.h)
("y1l" math.h)
("yn" math.h)
("ynf" math.h)
("ynl" math.h)
))
